#!/usr/bin/env bash
#/ Usage: script/rider
#/ Description: Enter the Violet dev shell
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
repo_root_dir="$( cd "${script_dir}/.." && pwd )"
cd "${repo_root_dir}"

if [ "$VIOLET_IN_DEV_SHELL" = "1" ]; then
    echo "You're already in the Violet dev shell!"
    exit 0
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            grep '^#/' <"$0" | cut -c4-
            exit 0
            ;;
        *)
            echo "ERROR: Unexpected argument '$1'."
            grep '^#/' <"$0" | cut -c4-
            exit 1
            ;;
    esac
done

if ! type nix &> /dev/null; then
    echo "The Violet dev shell requires Nix. Please install it and try again."
    exit 1
fi

exec nix develop