#!/usr/bin/env bash
#/ Usage: script/vi-to-il <vi-file>
#/ Description: Compile a Violet file and shows the IL
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
repo_root_dir="$( cd "${script_dir}/.." && pwd )"
cd "${repo_root_dir}"

set -euo pipefail

if [ "$VIOLET_IN_DEV_SHELL" != "1" ]; then
    echo "WARNING: Not in the violet dev shell. We recommend running 'script/shell' first."
    echo "Continue? [y/N]"
    read -r response
    if [[ ! "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
        exit 1
    fi
fi

dotnet run --project "./src/violetc" -- --reference "$VIOLET_DOTNET_SDK_PATH/packs/Microsoft.NETCore.App.Ref/8.0.0/ref/net8.0/System.Console.dll" --reference "$VIOLET_DOTNET_SDK_PATH/packs/Microsoft.NETCore.App.Ref/8.0.0/ref/net8.0/System.Runtime.dll" "$@"